# Generated by Django 4.1.1 on 2022-09-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solveamurder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='suspect',
            options={'verbose_name_plural': 'Suspects'},
        ),
        migrations.AlterModelOptions(
            name='victim',
            options={'verbose_name_plural': 'Victims'},
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='city_country',
            new_name='country',
        ),
    ]
